### ISSUE TITLE
add three good links

### ISSUE THREAD

**Issue by michaelschulte** [michaelschulte/EADMSummerSchool#3]
@amscheel can you please add three good links where people can get started and/or follow up on open science (eg SIPS page ;) ) - thanks!

**Comment by PascalKieslich** [comment]
One potentially helpful link:
https://how-to-open.science/
(an annotated collection of practical resources for researchers interested in using open practices put together by Felix Henninger)

**Comment by amscheel** [comment]
@PascalKieslich thanks for the tip, it's a great resource.
@michaelschulte I ended up adding more than 3, I hope you can forgive me...
